name: cutelligence
description: A barber app for face analysis and haircut recommendations
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  supabase_flutter: ^2.8.4
  image_picker: ^1.1.2
  google_ml_kit: ^0.20.0
  path_provider: ^2.0.15
  path: ^1.8.3
  uuid: ^4.5.1
  camera: ^0.11.1
  flutter_svg: ^2.0.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 